### PR TITLE
Fixes #25, Add Redis for last 20 user searches

### LINKED ISSUE #25: Add query field for latest searches
Maintain a Redis Queue for 20 latest searches, including the complete user data. Push to queue only when the user is found. 

Add query latestUsers with aruguments first: Int, with return data of user type. Write resolver to get users from redis.

Use: https://github.com/NodeRedis/node_redis

### PR DESCRIPTION
**Pull request by kapillamba4**
Closes #25

### CODE REVIEW

**Comment by kapillamba4** [comment]
@hereisnaman, review please.
```
query($user: Int!) {
    latest(user: $user) {
        ....
    }
}
```

**Comment by 0xnmn** [comment]
@kapillamba4 nice efforts. Please take care of the few things here:

1) create and pass redis client instance, getAsync through the context object, (see app/index.js). Pass it as a single object.
2) also latest query should have the argument first not user. Return latest n users data as array if n is provided 'first' argument, otherwise send first 20. For n > 20 send 20.

**Comment by kapillamba4** [comment]
@hereisnaman review please

**Comment by 0xnmn** [comment]
@kapillamba4 it sends the last n not latest n, may be you need to splice from first to length.

**Comment by kapillamba4** [comment]
@hereisnaman I have updated the PR, api will now provide all latest searches if $first is not provided and latest $first seaches if $first is provided

**Comment by 0xnmn** [comment]
Nice Work!

@championswimmer merging PR from @kapillamba4 for 500 bounty points.

**Pull request merged**
